spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrmanager?useUnicode=true&characterEncoding=utf8
    username: root
    password: 3.1415926
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.neusoft.hotelmanagementsystem.entity
#  配置MyBatis的相关的日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


